apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cuisine-ingress
  namespace: {{ include "cuisine.namespace" . }}
  labels:
    {{- include "cuisine.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`quisine.zenixweb.fr`)"
      kind: Rule
      services:
        - name: cuisine-frontend-service
          port: 80
      middlewares:
        - name: security-headers
