# values.yaml — Club Quisine (prod)
# Les images sont mises à jour automatiquement par la CI (build-and-push.yml)

namespace: quisine

frontend:
  image: ghcr.io/emmguardia/cuisine-front@sha256:3a8411f75723373940d465be9b0652729330681a29385ec5c5a2d1bf5ca02510
  imagePullPolicy: IfNotPresent
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  port: 8080
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"
    limits:
      cpu: "200m"
      memory: "64Mi"

backend:
  image: ghcr.io/emmguardia/cuisine-back@sha256:19b730f7b827cb6a89eeda7634569d73ad13165f59a15a65d555610740026ca5
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 3000
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
