# values.yaml — Club Quisine (prod)
# Les images sont mises à jour automatiquement par la CI (build-and-push.yml)

namespace: quisine

frontend:
  image: ghcr.io/emmguardia/cuisine-front@sha256:e63e624a5ebadaade9f1dd712c252caacb80003aa09f89871b1a1097f42c5376
  imagePullPolicy: IfNotPresent
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  port: 8080
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"
    limits:
      cpu: "200m"
      memory: "64Mi"

backend:
  image: ghcr.io/emmguardia/cuisine-back@sha256:612d8c01a58caf42429d8b80984b512d25121466d75e172616d985ce1dc56561
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 3000
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
