# values.yaml — Club Quisine (prod)
# Les images sont mises à jour automatiquement par la CI (build-and-push.yml)

namespace: quisine

frontend:
  image: ghcr.io/emmguardia/cuisine-front@sha256:686920ebc09fe008c2a307765b2aa5107b69490cf551a0c2ff8710f2b27254c8
  imagePullPolicy: IfNotPresent
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  port: 8080
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"
    limits:
      cpu: "200m"
      memory: "64Mi"

backend:
  image: ghcr.io/emmguardia/cuisine-back@sha256:6fe8a271aa02a1705253ea01492ef059205d5d2499dcad74b457c98a2b06f8ee
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 3000
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
